### ISSUE TITLE
Charliecloud simultaneous pull error

### ISSUE THREAD

**Issue by fa2k** [nextflow-io/nextflow#3566]
### Expected behavior and actual behavior

Running an nf-core pipeline would download the charliecloud images on-demand.

When multiple different processes are scheduled at the same time, requiring different images, there is an error message and nextflow stops (error shown below).

### Steps to reproduce the problem

When there are no local cached charliecloud images, the following command can reproduce the error:

    nextflow run nf-core/raredisease -r dev  --outdir raredisease --genome GRCh38 --analysis_type wgs  -profile test,charliecloud

### Program output 

```
Error executing process > 'NFCORE_RAREDISEASE:RAREDISEASE:CHECK_INPUT:SAMPLESHEET_CHECK (1)'

Caused by:
  Charliecloud failed to pull image
  command: ch-image pull -s /data/ephemeral/charlie quay.io/biocontainers/python:3.9--1 > /dev/null
  status : 1
  message:
    error: storage directory is already in use
    hint: concurrent instances of ch-image cannot share the same storage directory
```

### Environment 

* Nextflow version: 23.01.0-edge
* Java version: openjdk 11.0.13
* Operating system: Linux
* Bash version: 5.1.16(1)-release
* Charliecloud version: 0.30 (from conda)

### Additional context

It's possible to work around the problem by manually pulling all the required images before running nextflow.

**Comment by reidpr** [comment]
Just FYI older versions of Charliecloud wouldn't throw this error, but the lack of concurrency was still present, so they could just silently break stuff.

**Comment by reidpr** [comment]
Bot complaints notwithstanding, Charliecloud still does not support parallel access to its storage directory. So unless Nextflow has changed something, this bug is still present.

**Comment by nschan** [comment]
nextflow retries pulls 5 times with 30 seconds wait in between this should solve _most_ of the simulatenous pull erros. @fa2k do you still observe this with a recent release, or can this be closed?

**Comment by fa2k** [comment]
Thanks for following it up @nschan. I'm using nextflow 24.10.4, which seems to have this retrying behaviour. I'm running the test now, and it kept failing, but downloading more and more images. Now after launching the pipeline over 20 times, it doesn't seem to be progressing any more. I get an error about "can’t unlink: part_....", see below. I get the same error if I try to run the ch-image pull command manually, or run it for a different image.

```
ERROR ~ Error executing process > 'NFCORE_RAREDISEASE:RAREDISEASE:QC_BAM:UCSC_WIGTOBIGWIG (1)'

Caused by:
  Charliecloud failed to pull image
    command: ch-image pull -s /data0/paalmbj/tmp/work/charliecloud quay.io/biocontainers/ucsc-wigtobigwig:447--h2a80c09_1 > /dev/null
    status : 1
    hint   : Try and increase charliecloud.pullTimeout in the config (current is "20m")
    message:
      error: can’t unlink: part_8219a1ffe78e2830255b10f3d5156a5ca4ca3c932ac4fad251f6ae624c7572a1.tar.gz: No such file or directory



 -- Check '.nextflow.log' file for details
ERROR ~ Pipeline failed. Please refer to troubleshooting docs: https://nf-co.re/docs/usage/troubleshooting

 -- Check '.nextflow.log' file for details
```

**Comment by nschan** [comment]
Thanks @fa2k for testing. Which charliecloud version are you using?

> I'm running the test now, and it kept failing, but downloading more and more images. 
Do you mean it fails after the 5 retries? This can occur if there are a lot of images downloaded at the start of the pipeline, typically because many steps start directly with the input. Since the total retry * wait time is currently only 3 minutes, this may be sufficient to download maybe 2-3 images, but if it is 10 or so it will probably reach the retry limit and then nextflow will fail. It might be worth adding a parameter to control the number of pull retry-attempts, 5 might be a bit low.

> I get an error about "can’t unlink: part_....", see below. I get the same error if I try to run the ch-image pull command manually, or run it for a different image.
This is a charliecloud storage directory problem, which I have seen once, but I do not know what caused it; @reidpr might be able to elaborate on this.

**Comment by fa2k** [comment]
> > I'm running the test now, and it kept failing, but downloading more and more images.

> Do you mean it fails after the 5 retries? 

Yes exactly, it would download a few images, and then it gets to 5 retries for one of them, and stops. Indeed it woud be great to increase the attempts. The test profile is a real stress test for this because it has small data files. In real use, nextflow would spend more time running the tools and relatively less time downloading images.

**Comment by nschan** [comment]
> Yes exactly, it would download a few images, and then it gets to 5 retries for one of them, and stops. Indeed it woud be great to increase the attempts. The test profile is a real stress test for this because it has small data files. In real use, nextflow would spend more time running the tools and relatively less time downloading images.

I think there are some minor changes that have accumulated to improve nextflow's charliecloud driver, and I think adding a way to control number of retries should be straight-forward and seems good for usability. I agree that it is particular an issue for test datasets etc, but it can also happen for proper runs if there are large images pulled, or just many parallel initial steps.

**Comment by reidpr** [comment]
> > I get an error about "can’t unlink: part_....", see below. I get the same error if I try to run the ch-image pull command manually, or run it for a different image.
> 
> This is a charliecloud storage directory problem, which I have seen once, but I do not know what caused it; [@reidpr](https://github.com/reidpr) might be able to elaborate on this.

This looks like Charliecloud [issue #1925](https://gitlab.com/charliecloud/main/-/issues/1925) which is fixed in main and will be included in the upcoming 0.40.

**Comment by jfouret** [comment]
It's still an issue. I had this problem when I migrated to an academic cluster using charliecloud only.
The solution a colleague pointed out to me was a script that scan the nextflow project to pull all images in the shared cache :s.
@reidpr is it not possible to change ch-image adding a wait and retry mechanism in case of lock ?

**Comment by nschan** [comment]
The pre-pull approach is probably the most convenient for the time being.

The container approach in nextflow, where containers are pulled possibly in parallel when first required, simply does not work very well with charlieclouds cache. It would be possible to increase the number of attempts by nextflow to a number larger than 5. Probably this should be an option, but at the time I had assumed that 5 would be sufficient.

**Comment by reidpr** [comment]
> [@reidpr](https://github.com/reidpr) is it not possible to change ch-image adding a wait and retry mechanism in case of lock ?

Nobody’s asked previously, but this would be pretty straightforward. Can you file a bug on Charliecloud? Also a merge request would be quite welcome.

Another straightforward change would be for `ch-image` to accept multiple images to pull on the same command line.

**Comment by jfouret** [comment]
https://gitlab.com/charliecloud/charliecloud/-/work_items/2111

regarding the second point, it would not solve anything here because in nextflow the task can be distributed on different nodes and then the storage is not mandatory distributed across node, each node can have its local charliecloud cache and that is why the ch-image pull does not live in the orchestration process but rather in the tasks that are distributed. (In my case the cache lives in a distributed storage shared across nodes but it's not a rule)
