### ISSUE TITLE
Nested Environment Module names are not loaded properly

### ISSUE THREAD

**Issue by apeltzer** [nextflow-io/nextflow#489]
Hi everyone,

I tried executing a Singularity container with a basic script on our PBS cluster. After creating the script, I created a configuration file 

```
process { 
executor = 'pbs' 
module = 'qbic/singularity/2.4' 
container = '/share/test/testcontainer.simg' 
cpus = 8 
memory = 32.GB 
time = 24.h 
queue = 'cfc' 
}
```

It seems to be problematic, that NF can't find the module we need to load for getting singularity to run on our cluster. I typically load it like this `module load qbic/singularity/2.4` or similar. 

If I check the '.command.env' file, I find this:

`... nxf_module_load qbic singularity 2.4`
(which should have `/` in between of course).

**Comment by pditommaso** [comment]
The problem is that NF expected the module name as `name/version` with a single slash. 

Unfortunately I don't have an environment to test your condition, could you make this test. Save in a script snippet: 

```
set -x

nxf_module_load(){
  local mod=$1
  local ver=${2:-}
  local new_module="$mod"; [[ $ver ]] && new_module+="/$ver"

  if [[ ! $(module list 2>&1 | grep -o "$new_module") ]]; then
    old_module=$(module list 2>&1 | grep -Eo "$mod\/[^\( \n]+" || true)
    if [[ $ver && $old_module ]]; then
      module switch $old_module $new_module
    else
      module load $new_module
    fi
  fi
}

nxf_module_load qbic/singularity 2.4
```

then execute and post the output here?

**Comment by apeltzer** [comment]
sh test_paolo.sh 
    + nxf_module_load qbic/singularity 2.4 
    + local mod=qbic/singularity
    + local ver=2.4
    + local new_module=qbic/singularity
    + [[ -n 2.4 ]]
    + new_module+=/2.4
    ++ module list
    ++ grep -o qbic/singularity/2.4
    + [[ ! -n '' ]]
    ++ module list
    ++ grep -Eo 'qbic/singularity\/[^\( \n]+'
    ++ true
    + old_module=
    + [[ -n 2.4 ]]
    + [[ -n '' ]]
    + module load qbic/singularity/2.4
    ++ /usr/share/Modules/bin/modulecmd-wrapper bash load qbic/singularity/2.4
    + eval LOADEDMODULES=qbic/singularity/2.4 ';export' 
    'LOADEDMODULES;PATH=/lustre_cfc/software/qbic/singularity/2.4/bin:/usr/lib64/qt-
    3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/home-link/iiipe01/bin' ';export' 
    'PATH;SINGULARITY_BIN_DIR=/lustre_cfc/software/qbic/singularity/2.4/bin' ';export' 
    'SINGULARITY_BIN_DIR;SINGULARITY_VERSION=2.4' ';export' 
    'SINGULARITY_VERSION;_LMFILES_=/lustre_cfc/software/qbic/modulefiles/qbic/singularity/2.4' 
    ';export' '_LMFILES_;'
    ++ LOADEDMODULES=qbic/singularity/2.4
    ++ export LOADEDMODULES
    ++ PATH=/lustre_cfc/software/qbic/singularity/2.4/bin:/usr/lib64/qt-
    3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/home-link/iiipe01/bin
    ++ export PATH
    ++ SINGULARITY_BIN_DIR=/lustre_cfc/software/qbic/singularity/2.4/bin
    ++ export SINGULARITY_BIN_DIR
    ++ SINGULARITY_VERSION=2.4
    ++ export SINGULARITY_VERSION
    ++ _LMFILES_=/lustre_cfc/software/qbic/modulefiles/qbic/singularity/2.4
    ++ export _LMFILES_

**Comment by pditommaso** [comment]
I see `module load qbic/singularity/2.4`, it seems to work properly in this way, right?

**Comment by apeltzer** [comment]
Yes! I added a small statement to your script (`singularity --version`) and it states `2.4-dist` which is correct. This should work now :+1:

**Comment by pditommaso** [comment]
OK, providing a patch soon.

**Comment by pditommaso** [comment]
I've uploaded a new build (4664) that should fix this problem. You may want to give a try prepending the var `NXF_VER=0.26.0-SNAPSHOT` to usual NF commands, eg 

```
NXF_VER=0.26.0-SNAPSHOT nextflow run .. etc
```

**Comment by apeltzer** [comment]
Can confirm that this resolves the issue !

**Comment by apeltzer** [comment]
Hmm, still not working. I don't know why it doesn't load the module beforehand. Maybe you see something? 


[command.env.txt](https://github.com/nextflow-io/nextflow/files/1410549/command.env.txt)
[command.err.txt](https://github.com/nextflow-io/nextflow/files/1410550/command.err.txt)
[command.log.txt](https://github.com/nextflow-io/nextflow/files/1410551/command.log.txt)
[command.run.txt](https://github.com/nextflow-io/nextflow/files/1410552/command.run.txt)
[command.sh.txt](https://github.com/nextflow-io/nextflow/files/1410553/command.sh.txt)

**Comment by pditommaso** [comment]
Are you loading singularity as a module to run a NF task? that's not possible unfortunately.

**Comment by pditommaso** [comment]
However it should work by using [beforeScript](https://www.nextflow.io/docs/latest/process.html#beforescript) directive.

**Comment by apeltzer** [comment]
Oh, okay. I thought this was the way to do it. Yes, I thought this would load the module for the execution of the job & then allow me to run anything with Singularity. 

I've run into another issue with that: When using the `beforeScript` directive, the shub command won't work unfortunately. So something like this in the conf:

`container = 'shub://qbicsoftware/qbic-singularity-megSAP'
`

in the config doesn't work either.

**Comment by pditommaso** [comment]
Please include the `.nextflow.log` and tasks `.command.xxx` files

**Comment by apeltzer** [comment]
[nextflow.log.txt](https://github.com/nextflow-io/nextflow/files/1411024/nextflow.log.txt)

There is no .command.XXX file unfortunately. The config I used can be found here.

[cfc.config.txt](https://github.com/nextflow-io/nextflow/files/1411026/cfc.config.txt)

 I'm able to pull the container manually after loading the singularity environment on our cluster, too.

**Comment by pditommaso** [comment]
I see. As long as you out a *remote* container image, NF will run the `singularity` command in the same computer when NF is running (I guess the head node) in which  singularity is not available. 

If you are not allowed to run it in the node, you will need to download the image manually and use the image file path in the NF config file.

**Comment by apeltzer** [comment]
Ah I guess I'm understanding the thing here. So that means, we can't use NF in a way to download the image on a "per use case" basis on the actual compute node(s)? Or is there something you can recommend doing here?

**Comment by pditommaso** [comment]
Singularity images are supposed to be store through a shared file system otherwise you will have a download of the same image in each different computing node. For this reason NF is doing once in the head node where it is running. 

It should be fine to have singularity in the head node to pull image. This would solve the problem. If it's not your case, you will need to download the images manually and use the file path instead of a URL in the config file.

**Comment by apeltzer** [comment]
Okay,  I guess I could just load the module on the headnode then, run NF to submit the jobs (and pull containers if thats required ...) and then be happy about it :-) 

Thanks for all your help here!

**Comment by pditommaso** [comment]
welcome!
