### ISSUE TITLE
nextflow config - also parse nf script

### ISSUE THREAD

**Issue by ewels** [nextflow-io/nextflow#632]
The `nextflow config` command is great for checking that everything is defined properly in the config files. However, it _only_  parses the config files and not the nextflow script.

It would be great if this command also parsed the nextflow script and added these configuration variables to the output as well.

Asking for the nf-core project so that we can check stuff like pipeline version and minimum nextflow versions [are defined](https://github.com/SciLifeLab/NGI-MethylSeq/blob/628f23bfcf687d03fab8ba9e33d6acec073212b2/bismark.nf#L21-L26).

**Comment by pditommaso** [comment]
Need to check how much this is feasible to fetch the those values it's not enough to parse the script it requires to execute it. 

I would advice to externalise all parameters with a proper `params` definition in the config file.

**Comment by ewels** [comment]
> I would advice to externalise all parameters with a proper `params` definition in the config file.

Yes, you're probably right about that. Ok, so not so necessary then I guess.

Side note - it looks like `nextflow config` doesn't return anything from the `process` scope, is this right? Any reason for that?

**Comment by pditommaso** [comment]
Well, it should.

**Comment by ewels** [comment]
> I would advice to externalise all parameters with a proper `params` definition in the config file.

What about stuff that I don't want people to be able to overwrite? eg. a version number for the pipeline. Without the `params.` prefix it is not passed through to the nextflow script, right? But if I call it `params.version` then people can overwrite it on the command line, potentially causing all kinds of weird things to happen.

**Comment by ewels** [comment]
> Well, it should.

You're right, and it does. Sorry - I was grepping and had introduced a bug by accident, so the grep returned nothing. 🙄

**Comment by ewels** [comment]
> What about stuff that I don't want people to be able to overwrite?

Any recommendations on this?

**Comment by pditommaso** [comment]
Hi, sorry a bit overwhelmed today .. :) I see that could be useful, but it may be quite tricky to implement and frankly I don't see either a quick workaround.

**Comment by ewels** [comment]
Is the `manifest` scope available in the pipeline execution? We could add this kind of pipeline metadata there, eg. `manifest.version` and `manifest.minimum_nf_version` etc. If we can add any arbitrary key-value pair there then that would be fine.

I just tried this and they show up in `nextflow config` but don't seem to be accessible when running the pipeline:

```
ERROR ~ No such variable: manifest
```

**Comment by pditommaso** [comment]
I'm a bit lost here, there's are 4 different topics: 

1) include script params in the `nextflow config` output
2) nextflow config doesn't return anything from the process scope
3) *costant* parameters 
4) manifest metadata .. 

which is solved and which is not (in this case it should go in a separate issue) ?

**Comment by ewels** [comment]
1 - not solved, but maybe not so important if I change the way that I write pipelines. 

2 - solved (just a silly mistake from me)

4 is a possible solution for 3.

**Comment by pditommaso** [comment]
1. there should be no way to parse the script parameters without triggering the workflow execution (sorry if I had suggested something different before) 
2. ok 
3. Constant parameters can be useful in some context, but it would require some hacks that I need to investigate. However there's a so long list of bugs/feature requests that I cannot prioritise it.
4. it could done, but menifest metadata can be overridden like any other config properties, therefore I'm not sure it will solve your problem.

**Comment by ewels** [comment]
ok great, thanks for the clarifications. Re: constant params / manifest metadata - I was mostly worried about the ease with which `params` can be overwritten on the command line. I tend to view anything done with these as being deliberately user configurable. I guess you mean that manifest metadata can be overwritten by user config files, but this feels like less of a problem as it requires more effort.

Anyway - I think I can solve everything by (a) moving all vars into `nextflow.config` `params` and (b) being less paranoid 😆
